const express = require("express");
const { addDistrict, getDistricts, updateDistrict, deleteDistrict, getCentersByDistrict, addPlace, fetchPlaces, updatePlace, deletePlace, fetchItems, deleteItem, updateItem, addItem, addDisaster, fetchDisasterTypes, updateDisaster, deleteDisaster, getDashboardStats, adminRegister, getVolunteers, getDisasters, getCenters, getAllRequests, getAllCamps, getAnalyticsStats } = require("../controllers/admin.controller");
const { adminAuth } = require("../middlewares/adminAuth");
const router = express.Router();

router.get("/dashboard-stats", adminAuth, getDashboardStats);
router.get("/analytics-stats", adminAuth, getAnalyticsStats);
router.get("/all-centers", adminAuth, getCenters);
router.get("/all-requests", adminAuth, getAllRequests);
router.get("/all-camps", adminAuth, getAllCamps);
router.post("/addDistrict", adminAuth, addDistrict);
router.get("/districts", getDistricts);
router.put("/district/:id", adminAuth, updateDistrict);
router.delete("/district/:id", adminAuth, deleteDistrict);
router.get("/centers/:districtId", getCentersByDistrict);
router.post("/item", adminAuth, addItem);
router.get("/items", adminAuth, fetchItems);
router.put("/item/:id", adminAuth, updateItem);
router.delete("/item/:id", adminAuth, deleteItem);
router.post("/place/:id", adminAuth, addPlace);
router.get("/places/:districtId", adminAuth, fetchPlaces);
router.put("/place/:id", adminAuth, updatePlace);
router.delete("/place/:districtId", adminAuth, deletePlace);
router.post("/new-disaster", adminAuth, addDisaster);
router.get("/disaster-types", fetchDisasterTypes);
router.put("/disaster-type/:id", adminAuth, updateDisaster);
router.delete("/disaster-type/:id", adminAuth, deleteDisaster);
router.get("/volunteers",adminAuth, getVolunteers);
router.get("/disasters",adminAuth, getDisasters);
router.post("/register", adminRegister);
module.exports = router;
